import { collection, doc, getDoc, getDocs, limit, orderBy, query, runTransaction, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { can } from "../../permissions.js";
import { auth, db } from "../../services/firebase.js";
import { getMarketingKnowledge } from "./knowledgeService.js";
import { getTheoryVersion } from "./theoryService.js";
import { approveCampaignPlan, buildCampaignPlanningContext, validateAnswers, validateCampaignPlan, validateQuestions } from "./campaignPlanningDomain.js";

const CAMPAIGNS="metaCampaignProjects",THEORIES="metaAdTheories",AI_USAGE="aiUsage";
const profileName=p=>p?.name||p?.email||"Usuario";
const stateRef=id=>doc(db,CAMPAIGNS,id,"planning","state");
const planRef=(id,revision)=>doc(db,CAMPAIGNS,id,"plans",`r${revision}`);
const audit=(p,campaignId,action,title,description="")=>({action,title,description,moduleId:"marketing",entityType:"metaCampaignProject",entityId:campaignId,userId:p.id,userName:profileName(p),status:"completed",createdAt:serverTimestamp()});
function requireAction(profile,action,message){if(!can(profile,"marketing",action)){const e=new Error(message);e.code="permission-denied";throw e;}}
const serialize=value=>JSON.parse(JSON.stringify(value??null));
function planningUsage(profile,campaignId,operation,result={},success=true,errorCode=null){const u=result.usage||{},inputTokens=Number.isInteger(u.inputTokens)?u.inputTokens:0,outputTokens=Number.isInteger(u.outputTokens)?u.outputTokens:0;return{schemaVersion:1,operation,campaignId,userId:profile.id,userName:profileName(profile),model:String(u.model||result.model||"unknown").slice(0,120),inputTokens,outputTokens,totalTokens:Number.isInteger(u.totalTokens)?u.totalTokens:inputTokens+outputTokens,actualCostUsd:typeof u.actualCostUsd==="number"&&Number.isFinite(u.actualCostUsd)&&u.actualCostUsd>=0?u.actualCostUsd:null,success,errorCode:errorCode?String(errorCode).slice(0,120):null,responseId:u.responseId?String(u.responseId).slice(0,180):null,createdAt:serverTimestamp()};}
async function authorizedFetch(body){const user=auth.currentUser;if(!user){const e=new Error("Tu sesión venció. Volvé a iniciar sesión.");e.code="unauthenticated";throw e;}const idToken=await user.getIdToken();const response=await fetch("/.netlify/functions/campaign-planner",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${idToken}`},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.message||"No pudimos completar la planificación con IA.");e.code=data.code||`planner-http-${response.status}`;e.userMessage=data.message;throw e;}return data;}

export async function listActiveTheoryChoices(profile){requireAction(profile,"metaAdsView","No tenés permiso para ver metodologías.");const snap=await getDocs(query(collection(db,THEORIES),where("status","==","active"),limit(10)));return snap.docs.filter(x=>x.data().activeVersionId).map(x=>({id:x.id,name:x.data().name,versionId:x.data().activeVersionId,version:x.data().activeVersion}));}
export async function loadCampaignPlanningWorkspace(profile,campaign){requireAction(profile,"metaAdsView","No tenés permiso para ver la planificación.");const stateSnap=await getDoc(stateRef(campaign.id)),state=stateSnap.exists()?{id:stateSnap.id,...stateSnap.data()}:null,plansSnap=await getDocs(query(collection(db,CAMPAIGNS,campaign.id,"plans"),orderBy("revision","desc"),limit(10))),plans=plansSnap.docs.map(x=>({id:x.id,...x.data()}));let context=null,theoryVersion=null;if(campaign.theoryId&&campaign.theoryVersionId){try{theoryVersion=await getTheoryVersion(profile,campaign.theoryId,campaign.theoryVersionId);const knowledge=await getMarketingKnowledge(profile,{productId:campaign.productId||null});context=buildCampaignPlanningContext({campaign,knowledge,theory:{id:campaign.theoryId,versionId:campaign.theoryVersionId,version:campaign.theoryVersion,name:campaign.theoryNameSnapshot,config:theoryVersion.config},previousAnswers:state?.answers||{}});}catch{context=null;}}return{state,plans,context,theoryVersion};}

export async function startCampaignPlanning(profile,campaign,theoryChoice){requireAction(profile,"metaAdsPlanCampaign","No tenés permiso para planificar campañas.");if(campaign.status!=="draft"){const e=new Error("La planificación sólo se inicia desde una campaña en borrador.");e.code="campaign-state-invalid";throw e;}if(!campaign.productId){const e=new Error("Elegí un producto antes de planificar la campaña.");e.code="product-required";throw e;}const theory=await getTheoryVersion(profile,theoryChoice.id,theoryChoice.versionId);if(theory.status!=="active"||theory.version!==theoryChoice.version){const e=new Error("La metodología elegida ya no está activa. Recargá antes de continuar.");e.code="theory-not-active";throw e;}const now=serverTimestamp(),name=profileName(profile),b=writeBatch(db);b.update(doc(db,CAMPAIGNS,campaign.id),{status:"planning",planningStatus:"context_ready",theoryId:theoryChoice.id,theoryVersionId:theoryChoice.versionId,theoryVersion:theory.version,theoryNameSnapshot:theoryChoice.name||"Metodología",latestPlanRevision:0,approvedPlanRevision:null,lastPlanningAt:now,lastPlanningBy:profile.id,updatedBy:profile.id,updatedByName:name,updatedAt:now});b.set(stateRef(campaign.id),{schemaVersion:1,campaignId:campaign.id,status:"context_ready",theoryId:theoryChoice.id,theoryVersionId:theoryChoice.versionId,theoryVersion:theory.version,questions:[],answers:{},latestPlanRevision:0,approvedPlanRevision:null,createdBy:profile.id,createdByName:name,createdAt:now,updatedBy:profile.id,updatedByName:name,updatedAt:now});b.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,"metaAds.planning.started","Planificación iniciada",`Metodología ${theoryChoice.name||theoryChoice.id} v${theory.version}`));await b.commit();}

export async function generateCampaignQuestions(profile,campaign){requireAction(profile,"metaAdsPlanCampaign","No tenés permiso para preparar preguntas.");const result=await authorizedFetch({operation:"generateQuestions",campaignId:campaign.id,requestId:crypto.randomUUID()}),validation=validateQuestions(result.questions||[],{allowedKeys:Array.isArray(result.allowedKeys)?result.allowedKeys:null});if(!validation.valid){const e=new Error(validation.errors[0]);e.code="questions-invalid";throw e;}const b=writeBatch(db),now=serverTimestamp(),nextStatus=validation.value.length?"questions_ready":"answers_ready";b.update(stateRef(campaign.id),{questions:validation.value,answers:{},status:nextStatus,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:now});b.update(doc(db,CAMPAIGNS,campaign.id),{planningStatus:nextStatus,lastPlanningAt:now,lastPlanningBy:profile.id,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:now});b.set(doc(collection(db,AI_USAGE)),planningUsage(profile,campaign.id,"campaign_questions",result));b.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,"metaAds.planning.questions_generated","Preguntas preparadas",`${validation.value.length} preguntas`));await b.commit();return validation.value;}

export async function saveCampaignAnswers(profile,campaign,questions,answers){requireAction(profile,"metaAdsPlanCampaign","No tenés permiso para responder la planificación.");const validation=validateAnswers(questions,answers);if(!validation.valid){const e=new Error(validation.errors[0]);e.code="answers-invalid";e.validationErrors=validation.errors;throw e;}const now=serverTimestamp(),b=writeBatch(db);b.update(stateRef(campaign.id),{answers:validation.value,status:"answers_ready",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:now});b.update(doc(db,CAMPAIGNS,campaign.id),{planningStatus:"answers_ready",lastPlanningAt:now,lastPlanningBy:profile.id,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:now});b.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,"metaAds.planning.answers_saved","Respuestas guardadas"));await b.commit();return validation.value;}

async function persistGeneratedPlan(profile,campaign,result,{regenerated=false}={}){const name=profileName(profile);return runTransaction(db,async tx=>{const sr=stateRef(campaign.id),cr=doc(db,CAMPAIGNS,campaign.id),ss=await tx.get(sr),cs=await tx.get(cr);if(!ss.exists()||!cs.exists())throw new Error("La planificación ya no está disponible.");const state=ss.data(),current=cs.data();if(state.theoryVersionId!==current.theoryVersionId){const e=new Error("La metodología asociada cambió.");e.code="theory-mismatch";throw e;}const tr=doc(db,THEORIES,current.theoryId,"versions",current.theoryVersionId),ts=await tx.get(tr);if(!ts.exists()){const e=new Error("La metodología asociada ya no existe.");e.code="theory-not-found";throw e;}const validation=validateCampaignPlan(result.plan,{theoryConfig:ts.data().config});if(!validation.valid){const e=new Error(validation.errors[0]);e.code="campaign-plan-invalid";e.validationErrors=validation.errors;throw e;}const revision=(Number(state.latestPlanRevision)||0)+1,pr=planRef(campaign.id,revision),now=serverTimestamp();tx.set(pr,{schemaVersion:1,campaignId:campaign.id,revision,status:"draft",theoryId:current.theoryId,theoryVersionId:current.theoryVersionId,theoryVersion:current.theoryVersion,plan:serialize(validation.value),model:String(result.model||result.usage?.model||"unknown").slice(0,120),responseId:result.responseId?String(result.responseId).slice(0,180):null,createdBy:profile.id,createdByName:name,createdAt:now,updatedBy:profile.id,updatedByName:name,updatedAt:now,approvedBy:null,approvedByName:null,approvedAt:null});tx.update(sr,{status:"plan_ready",latestPlanRevision:revision,updatedBy:profile.id,updatedByName:name,updatedAt:now});tx.update(cr,{planningStatus:"plan_ready",latestPlanRevision:revision,lastPlanningAt:now,lastPlanningBy:profile.id,updatedBy:profile.id,updatedByName:name,updatedAt:now});tx.set(doc(collection(db,AI_USAGE)),planningUsage(profile,campaign.id,"campaign_plan",result));tx.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,regenerated?"metaAds.planning.plan_regenerated":"metaAds.planning.plan_generated",regenerated?"Plan regenerado":"Plan generado",`Revisión ${revision}`));return revision;});}
export async function generateCampaignPlan(profile,campaign,{regenerated=false}={}){requireAction(profile,"metaAdsPlanCampaign","No tenés permiso para preparar la estrategia.");const result=await authorizedFetch({operation:"generatePlan",campaignId:campaign.id,requestId:crypto.randomUUID()}),revision=await persistGeneratedPlan(profile,campaign,result,{regenerated});return{revision,plan:result.plan};}

export async function editCampaignPlan(profile,campaign,planRevision,nextPlan,theoryConfig){requireAction(profile,"metaAdsPlanCampaign","No tenés permiso para editar el plan.");if(planRevision.status!=="draft"){const e=new Error("Un plan aprobado no se modifica. Regenerá una nueva revisión.");e.code="plan-immutable";throw e;}const validation=validateCampaignPlan(nextPlan,{theoryConfig});if(!validation.valid){const e=new Error(validation.errors[0]);e.code="campaign-plan-invalid";e.validationErrors=validation.errors;throw e;}const b=writeBatch(db),now=serverTimestamp();b.update(planRef(campaign.id,planRevision.revision),{plan:serialize(validation.value),updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:now});b.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,"metaAds.planning.plan_edited","Plan editado",`Revisión ${planRevision.revision}`));await b.commit();return validation.value;}

export async function approveCampaignPlanRevision(profile,campaign,planRevision){requireAction(profile,"metaAdsApprovePlan","No tenés permiso para aprobar planes.");return runTransaction(db,async tx=>{const cr=doc(db,CAMPAIGNS,campaign.id),sr=stateRef(campaign.id),pr=planRef(campaign.id,planRevision.revision),cs=await tx.get(cr),ss=await tx.get(sr),ps=await tx.get(pr);if(!cs.exists()||!ss.exists()||!ps.exists())throw new Error("El plan ya no está disponible.");const current=cs.data(),state=ss.data(),record=ps.data();if(record.status!=="draft"){const e=new Error("El plan ya fue aprobado.");e.code="plan-state-invalid";throw e;}if(record.theoryVersionId!==current.theoryVersionId||record.theoryVersionId!==state.theoryVersionId){const e=new Error("La versión de metodología no coincide.");e.code="theory-mismatch";throw e;}const tr=doc(db,THEORIES,current.theoryId,"versions",current.theoryVersionId),ts=await tx.get(tr);if(!ts.exists())throw new Error("La metodología asociada ya no está disponible.");const validation=validateCampaignPlan(record.plan,{theoryConfig:ts.data().config});if(!validation.valid){const e=new Error(validation.errors[0]);e.code="campaign-plan-invalid";throw e;}const approved=approveCampaignPlan(validation.value),now=serverTimestamp(),name=profileName(profile),nextStatus=current.status==="planning"?"creative":current.status;if(!["planning","creative"].includes(current.status)){const e=new Error("La campaña no está en un estado que permita aprobar el plan.");e.code="campaign-state-invalid";throw e;}tx.update(pr,{status:"approved",plan:serialize(approved),approvedBy:profile.id,approvedByName:name,approvedAt:now,updatedBy:profile.id,updatedByName:name,updatedAt:now});tx.update(sr,{status:"approved",approvedPlanRevision:record.revision,updatedBy:profile.id,updatedByName:name,updatedAt:now});tx.update(cr,{status:nextStatus,planningStatus:"approved",approvedPlanRevision:record.revision,lastPlanningAt:now,lastPlanningBy:profile.id,updatedBy:profile.id,updatedByName:name,updatedAt:now});tx.set(doc(collection(db,"auditLogs")),audit(profile,campaign.id,"metaAds.planning.plan_approved","Plan aprobado",`Revisión ${record.revision}`));return approved;});}

export async function getCampaignPlannerHealth(){try{const r=await fetch("/.netlify/functions/campaign-planner?health=1",{headers:{Accept:"application/json"}}),b=await r.json().catch(()=>({}));return{available:r.ok,configured:b.configured===true,questionModel:b.questionModel||"",planModel:b.planModel||"",pricingConfigured:b.pricingConfigured===true};}catch{return{available:false,configured:false,questionModel:"",planModel:"",pricingConfigured:false};}}
export function campaignPlannerFriendlyError(error){const c=error?.code||"";if(c==="permission-denied")return"No tenés permiso para realizar esta acción.";if(c==="unauthenticated")return"Tu sesión venció. Volvé a iniciar sesión.";if(c==="product-required")return"Elegí un producto antes de empezar a planificar.";if(c==="theory-not-active"||c==="theory-mismatch")return"La metodología cambió. Recargá la campaña antes de continuar.";if(c==="openai-key-missing")return"OpenAI todavía no está configurado en Netlify.";if(c==="openai-billing-required")return"La IA está configurada, pero la cuenta de API no tiene crédito disponible.";if(c==="openai-rate-limit")return"La IA recibió demasiadas solicitudes. Esperá un momento y probá de nuevo.";if(c==="openai-timeout")return"La IA tardó demasiado. Tus respuestas siguen guardadas; podés reintentar.";if(c==="questions-invalid"||c==="answers-invalid"||c==="campaign-plan-invalid")return error?.message||"La información generada no pasó las validaciones de seguridad.";if(c==="plan-immutable")return"Este plan ya está aprobado. Regenerá una nueva revisión para cambiarlo.";return error?.userMessage||error?.message||"No pudimos completar la planificación.";}
