import { collection, doc, getDoc, getDocs, limit, orderBy, query, runTransaction, serverTimestamp, startAfter, writeBatch } from "firebase/firestore";
import { can } from "../../permissions.js";
import { auth, db } from "../../services/firebase.js";
import { THEORY_COLLECTION, THEORY_PAGE_SIZE, THEORY_VERSION_PAGE_SIZE, buildCompiledReviewPatch, canActivateTheoryVersion, canApproveTheoryVersion, canCompileTheoryVersion, canCreateNextTheoryVersion, canEditTheoryVersion, createTheoryParentPayload, createTheoryVersionPayload, editableVersionPatch, hashTheorySource, nextTheoryVersionNumber, normalizeTheoryDescription, normalizeTheoryName, profileName, theoryVersionId } from "./theoryDomain.js";
import { assertValidTheoryConfig } from "./theorySchema.js";

export const AI_USAGE_COLLECTION="aiUsage";
const rows=s=>s.docs.map(x=>({id:x.id,...x.data()}));
function requireView(p){ if(!can(p,"marketing","metaAdsView")){ const e=new Error("No tenés permiso para ver metodologías."); e.code="permission-denied"; throw e; } }
function requireManage(p){ if(!can(p,"marketing","metaAdsManageTheory")){ const e=new Error("No tenés permiso para gestionar metodologías."); e.code="permission-denied"; throw e; } }
const vref=(theoryId,versionId)=>doc(db,THEORY_COLLECTION,theoryId,"versions",versionId);
const audit=(p,id,action,title,description="",entityType="metaAdsTheory")=>({action,title,description,moduleId:"marketing",entityType,entityId:id,userId:p.id,userName:profileName(p),status:"completed",createdAt:serverTimestamp()});

export async function listMetaAdsTheories(profile,{pageSize=THEORY_PAGE_SIZE,cursor=null}={}){ requireView(profile); const n=Math.max(1,Math.min(50,Number(pageSize)||THEORY_PAGE_SIZE)); const c=[orderBy("updatedAt","desc")]; if(cursor)c.push(startAfter(cursor)); c.push(limit(n)); const s=await getDocs(query(collection(db,THEORY_COLLECTION),...c)); return {items:rows(s),cursor:s.docs.at(-1)||null,hasMore:s.docs.length===n}; }
export async function getMetaAdsTheory(profile,theoryId){ requireView(profile); const s=await getDoc(doc(db,THEORY_COLLECTION,theoryId)); if(!s.exists()){const e=new Error("La metodología no existe.");e.code="not-found";throw e;} return {id:s.id,...s.data()}; }
export async function listTheoryVersions(profile,theoryId,{pageSize=THEORY_VERSION_PAGE_SIZE,cursor=null}={}){ requireView(profile); const n=Math.max(1,Math.min(25,Number(pageSize)||THEORY_VERSION_PAGE_SIZE)); const c=[orderBy("version","desc")]; if(cursor)c.push(startAfter(cursor)); c.push(limit(n)); const s=await getDocs(query(collection(db,THEORY_COLLECTION,theoryId,"versions"),...c)); return {items:rows(s),cursor:s.docs.at(-1)||null,hasMore:s.docs.length===n}; }
export async function getTheoryVersion(profile,theoryId,versionId){ requireView(profile); const s=await getDoc(vref(theoryId,versionId)); if(!s.exists()){const e=new Error("La versión no existe.");e.code="not-found";throw e;} return {id:s.id,...s.data()}; }

export async function createMetaAdsTheory(profile,{name,description="",sourceType="text",sourceName="",sourceText="",sourceSize=null}={}){ requireManage(profile); const sourceHash=await hashTheorySource(sourceText); const parentRef=doc(collection(db,THEORY_COLLECTION)); const parent=createTheoryParentPayload(profile,{name,description}); const version=createTheoryVersionPayload(profile,parentRef.id,{version:1,sourceType,sourceName,sourceText,sourceSize,sourceHash}); const b=writeBatch(db); b.set(parentRef,{...parent,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); b.set(vref(parentRef.id,"v1"),{...version,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); b.set(doc(collection(db,"auditLogs")),audit(profile,parentRef.id,"metaAds.theory.created","Metodología creada",parent.name)); await b.commit(); return parentRef.id; }

export async function saveTheoryVersion(profile,theory,version,input={}){ requireManage(profile); if(!canEditTheoryVersion(version)){const e=new Error("Esta versión es histórica o está bloqueada. Creá una nueva versión.");e.code="version-immutable";throw e;} const sourceText=input.sourceText??version.sourceText??""; const sourceHash=await hashTheorySource(sourceText); const patch=editableVersionPatch(version,{...input,sourceText,sourceHash}); const b=writeBatch(db); b.update(vref(theory.id,version.id),{...patch,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.update(doc(db,THEORY_COLLECTION,theory.id),{status:patch.status,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.set(doc(collection(db,"auditLogs")),audit(profile,theory.id,"metaAds.theory.version.updated","Versión actualizada",`v${version.version}`,"metaAdsTheoryVersion")); await b.commit(); }

export async function createNextTheoryVersion(profile,theory,sourceVersion){ requireManage(profile); if(!canCreateNextTheoryVersion(sourceVersion)){const e=new Error("Sólo se puede crear una nueva versión desde una versión aprobada, activa o histórica.");e.code="version-state-invalid";throw e;} return runTransaction(db,async tx=>{ const pr=doc(db,THEORY_COLLECTION,theory.id); const ps=await tx.get(pr); if(!ps.exists())throw new Error("La metodología ya no existe."); const n=nextTheoryVersionNumber(ps.data()),id=theoryVersionId(n),nr=vref(theory.id,id); const exists=await tx.get(nr); if(exists.exists())throw new Error("La nueva versión ya existe."); const payload=createTheoryVersionPayload(profile,theory.id,{version:n,sourceType:sourceVersion.sourceMetadata?.sourceType||"editor",sourceName:sourceVersion.sourceMetadata?.sourceName||"Nueva versión",sourceText:sourceVersion.sourceText||"",sourceSize:sourceVersion.sourceMetadata?.sourceSize??null,sourceHash:sourceVersion.sourceMetadata?.sourceHash||"",config:sourceVersion.config?assertValidTheoryConfig(sourceVersion.config):null,derivedFromVersionId:sourceVersion.id}); tx.set(nr,{...payload,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); tx.update(pr,{latestVersion:n,latestVersionId:id,status:"draft",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); tx.set(doc(collection(db,"auditLogs")),audit(profile,theory.id,"metaAds.theory.version.created","Nueva versión creada",`v${n} desde v${sourceVersion.version}`,"metaAdsTheoryVersion")); return id; }); }

export async function markTheoryCompiling(profile,theory,version){ requireManage(profile); if(!canCompileTheoryVersion(version)){const e=new Error("Esta versión no puede procesarse con IA.");e.code="version-state-invalid";throw e;} const b=writeBatch(db); b.update(vref(theory.id,version.id),{status:"compiling",compileError:null,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.update(doc(db,THEORY_COLLECTION,theory.id),{status:"compiling",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); await b.commit(); }

function usageRecord(profile,theory,version,result={},success=true,errorCode=null){ const u=result.usage||result.compilerMetadata||{}; const inputTokens=Number.isInteger(u.inputTokens)?u.inputTokens:0, outputTokens=Number.isInteger(u.outputTokens)?u.outputTokens:0; return {schemaVersion:1,operation:"theory_compile",theoryId:theory.id,theoryVersionId:version.id,userId:profile.id,userName:profileName(profile),model:String(u.model||result.model||"unknown").slice(0,120),inputTokens,outputTokens,totalTokens:Number.isInteger(u.totalTokens)?u.totalTokens:inputTokens+outputTokens,actualCostUsd:typeof u.actualCostUsd==="number"&&Number.isFinite(u.actualCostUsd)&&u.actualCostUsd>=0?u.actualCostUsd:null,success,errorCode:errorCode?String(errorCode).slice(0,120):null,responseId:u.responseId?String(u.responseId).slice(0,180):null,createdAt:serverTimestamp()}; }

export async function applyCompiledTheory(profile,theory,version,result){ requireManage(profile); const patch=buildCompiledReviewPatch({...version,status:"compiling"},result); const b=writeBatch(db); b.update(vref(theory.id,version.id),{...patch,updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.update(doc(db,THEORY_COLLECTION,theory.id),{status:"review",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.set(doc(collection(db,AI_USAGE_COLLECTION)),usageRecord(profile,theory,version,{...result,usage:patch.compilerMetadata})); b.set(doc(collection(db,"auditLogs")),audit(profile,theory.id,"metaAds.theory.compiled","Metodología procesada con IA",`v${version.version}`,"metaAdsTheoryVersion")); await b.commit(); }
export async function markTheoryCompileError(profile,theory,version,error,metadata={}){ requireManage(profile); const code=String(error?.code||"compile-error").slice(0,120),message=String(error?.userMessage||error?.message||"No se pudo procesar la metodología.").replace(/\s+/g," ").slice(0,300); const b=writeBatch(db); b.update(vref(theory.id,version.id),{status:"error",compileError:{code,message},updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.update(doc(db,THEORY_COLLECTION,theory.id),{status:"error",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.set(doc(collection(db,AI_USAGE_COLLECTION)),usageRecord(profile,theory,version,{usage:metadata},false,code)); await b.commit(); }

export async function approveTheoryVersion(profile,theory,version){ requireManage(profile); if(!canApproveTheoryVersion(version)){const e=new Error("La versión debe estar en revisión y ser válida antes de aprobarse.");e.code="version-state-invalid";throw e;} assertValidTheoryConfig(version.config); const b=writeBatch(db); b.update(vref(theory.id,version.id),{status:"approved",approvedBy:profile.id,approvedByName:profileName(profile),approvedAt:serverTimestamp(),updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.update(doc(db,THEORY_COLLECTION,theory.id),{status:"approved",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); b.set(doc(collection(db,"auditLogs")),audit(profile,theory.id,"metaAds.theory.approved","Metodología aprobada",`v${version.version}`,"metaAdsTheoryVersion")); await b.commit(); }

export async function activateTheoryVersion(profile,theory,version){ requireManage(profile); if(!canActivateTheoryVersion(version)){const e=new Error("Sólo se puede activar una versión aprobada o histórica.");e.code="version-state-invalid";throw e;} await runTransaction(db,async tx=>{ const pr=doc(db,THEORY_COLLECTION,theory.id),ps=await tx.get(pr); if(!ps.exists())throw new Error("La metodología ya no existe."); const current=ps.data(),tr=vref(theory.id,version.id),ts=await tx.get(tr); if(!ts.exists())throw new Error("La versión ya no existe."); const target=ts.data(); if(!["approved","archived"].includes(target.status)){const e=new Error("El estado cambió. Recargá antes de activar.");e.code="version-state-invalid";throw e;} assertValidTheoryConfig(target.config); if(current.activeVersionId&&current.activeVersionId!==version.id){ const ar=vref(theory.id,current.activeVersionId),as=await tx.get(ar); if(as.exists()&&as.data().status==="active")tx.update(ar,{status:"archived",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); } tx.update(tr,{status:"active",activatedBy:profile.id,activatedByName:profileName(profile),activatedAt:serverTimestamp(),updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); tx.update(pr,{activeVersion:target.version,activeVersionId:version.id,status:"active",updatedBy:profile.id,updatedByName:profileName(profile),updatedAt:serverTimestamp()}); tx.set(doc(collection(db,"auditLogs")),audit(profile,theory.id,target.status==="archived"?"metaAds.theory.reactivated":"metaAds.theory.activated",target.status==="archived"?"Versión histórica reactivada":"Metodología activada",`v${target.version}`,"metaAdsTheoryVersion")); }); }

export async function getActiveTheoryConfig(profile,theoryId){ const theory=await getMetaAdsTheory(profile,theoryId); if(!theory.activeVersionId)return null; const version=await getTheoryVersion(profile,theoryId,theory.activeVersionId); return {theoryId,theoryName:theory.name,versionId:version.id,version:version.version,config:assertValidTheoryConfig(version.config)}; }

async function authorizedFetch(url,options={}){ const user=auth.currentUser; if(!user){const e=new Error("Tu sesión venció. Volvé a iniciar sesión.");e.code="unauthenticated";throw e;} const idToken=await user.getIdToken(); return fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${idToken}`}}); }
export async function getTheoryCompilerHealth(){ try{ const r=await fetch("/.netlify/functions/theory-compiler?health=1",{headers:{Accept:"application/json"}}),b=await r.json().catch(()=>({})); return {available:r.ok,configured:b.configured===true,model:b.model||"gpt-5.6-luna",pricingConfigured:b.pricingConfigured===true,inputUsdPerMToken:typeof b.inputUsdPerMToken==="number"?b.inputUsdPerMToken:null,outputUsdPerMToken:typeof b.outputUsdPerMToken==="number"?b.outputUsdPerMToken:null}; }catch{return {available:false,configured:false,model:"gpt-5.6-luna",pricingConfigured:false,inputUsdPerMToken:null,outputUsdPerMToken:null};} }
export async function compileTheoryVersion(profile,theory,version){ requireManage(profile); if(!canCompileTheoryVersion(version)){const e=new Error("Esta versión no se puede procesar.");e.code="version-state-invalid";throw e;} const sourceText=String(version.sourceText||"").trim(); if(!sourceText){const e=new Error("Agregá texto antes de procesar.");e.code="source-empty";throw e;} await markTheoryCompiling(profile,theory,version); let metadata={}; try{ const r=await authorizedFetch("/.netlify/functions/theory-compiler",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({theoryId:theory.id,versionId:version.id,theoryName:theory.name,sourceType:version.sourceMetadata?.sourceType||"text",sourceName:version.sourceMetadata?.sourceName||"Fuente",sourceHash:version.sourceMetadata?.sourceHash||null,sourceText})}); const body=await r.json().catch(()=>({})); metadata=body.usage||{}; if(!r.ok){const e=new Error(body.message||"No se pudo procesar la metodología con IA.");e.code=body.code||`compiler-http-${r.status}`;e.userMessage=body.message;throw e;} const result={config:assertValidTheoryConfig(body.config),usage:{...body.usage,model:body.model||body.usage?.model,responseId:body.responseId||body.usage?.responseId,compilerVersion:body.compilerVersion||"1"}}; await applyCompiledTheory(profile,theory,version,result); return result; }catch(e){ await markTheoryCompileError(profile,theory,version,e,metadata).catch(()=>{}); throw e; } }
export function theoryFriendlyError(error){ const c=error?.code||""; if(c==="permission-denied")return "No tenés permiso para realizar esta acción."; if(c==="unauthenticated")return "Tu sesión venció. Volvé a iniciar sesión."; if(c==="version-immutable")return "Esta versión es histórica. Creá una nueva versión para modificarla."; if(c==="source-empty")return "Agregá texto de metodología antes de procesar."; if(c==="openai-key-missing")return "OpenAI todavía no está configurado en Netlify."; if(c==="openai-rate-limit")return "OpenAI alcanzó temporalmente su límite. Probá más tarde."; if(c==="openai-timeout")return "OpenAI tardó demasiado. Tu texto sigue guardado; podés reintentar."; if(c==="openai-schema-invalid"||c==="theory-config-invalid")return "La IA devolvió una configuración inválida. No se guardó como válida."; if(c==="not-found")return "La metodología o versión ya no está disponible."; return error?.userMessage||error?.message||"No pudimos completar la operación."; }
export {normalizeTheoryName,normalizeTheoryDescription};
