export const THEORY_CONFIG_SCHEMA_VERSION = 1;
export const THEORY_LIMITS = Object.freeze({ sourceCharacters: 60000, sourceBytes: 3000000, pdfPages: 80, name: 120, description: 4000, instruction: 4000, requirementCount: 80, ruleCount: 80, count: 100, durationSeconds: 900 });

const SAFE_KEY=/^[a-z][a-z0-9_-]{1,63}$/i;
const DANGEROUS=/<\s*script\b|javascript\s*:|data\s*:\s*text\/html|on[a-z]+\s*=/i;
const TOP=["schemaVersion","platform","name","description","campaignRules","creativeRequirements","validationRules","questionPolicy","testingRules","recommendationRules","metadata"];
const RULE=["key","label","instructions","appliesToObjectives","appliesToPlatforms"];
const REQ=["key","label","required","minCount","recommendedCount","maxCount","duration","instructions"];
const DUR=["minSeconds","idealSeconds","maxSeconds"];

const str=(v,max=4000)=>typeof v==="string"?v.replace(/\u0000/g,"").replace(/\r\n?/g,"\n").trim().slice(0,max):"";
const arr=(v,max=80,len=300)=>Array.isArray(v)?[...new Set(v.map(x=>str(x,len)).filter(Boolean))].slice(0,max):[];
const extra=(o,keys)=>o&&typeof o==="object"&&!Array.isArray(o)?Object.keys(o).filter(k=>!keys.includes(k)):[];
const dangerous=v=>typeof v==="string"&&DANGEROUS.test(v);
function text(v,path,errors,{required=false,max=4000}={}){ if(typeof v!=="string") return errors.push(`${path}: debe ser texto.`); if(required&&!v.trim()) errors.push(`${path}: no puede estar vacío.`); if(v.length>max) errors.push(`${path}: supera el máximo permitido.`); if(dangerous(v)) errors.push(`${path}: contiene contenido no permitido.`); }
function key(v,path,errors){ if(typeof v!=="string"||!SAFE_KEY.test(v)) errors.push(`${path}: identificador inválido.`); }
function stringList(v,path,errors,max=50,len=80){ if(!Array.isArray(v)) return errors.push(`${path}: debe ser una lista.`); if(v.length>max) errors.push(`${path}: demasiados elementos.`); v.forEach((x,i)=>text(x,`${path}[${i}]`,errors,{required:true,max:len})); }
function ruleList(v,path,errors){ if(!Array.isArray(v)) return errors.push(`${path}: debe ser una lista.`); if(v.length>THEORY_LIMITS.ruleCount) errors.push(`${path}: demasiadas reglas.`); const seen=new Set(); v.forEach((r,i)=>{ const p=`${path}[${i}]`; if(!r||typeof r!=="object"||Array.isArray(r)) return errors.push(`${p}: debe ser un objeto.`); const ex=extra(r,RULE); if(ex.length) errors.push(`${p}: claves desconocidas: ${ex.join(", ")}.`); key(r.key,`${p}.key`,errors); if(seen.has(r.key)) errors.push(`${p}.key: repetida.`); seen.add(r.key); text(r.label,`${p}.label`,errors,{required:true,max:160}); text(r.instructions,`${p}.instructions`,errors,{max:THEORY_LIMITS.instruction}); stringList(r.appliesToObjectives,`${p}.appliesToObjectives`,errors,30,80); stringList(r.appliesToPlatforms,`${p}.appliesToPlatforms`,errors,20,80); }); }
function duration(d,path,errors){ if(!d||typeof d!=="object"||Array.isArray(d)) return errors.push(`${path}: debe ser un objeto.`); const ex=extra(d,DUR); if(ex.length) errors.push(`${path}: claves desconocidas: ${ex.join(", ")}.`); for(const k of DUR){ const v=d[k]; if(v!==null&&(typeof v!=="number"||!Number.isFinite(v)||v<0||v>THEORY_LIMITS.durationSeconds)) errors.push(`${path}.${k}: duración inválida.`); } const a=d.minSeconds,b=d.idealSeconds,c=d.maxSeconds; if(a!=null&&b!=null&&a>b) errors.push(`${path}: minSeconds no puede superar idealSeconds.`); if(b!=null&&c!=null&&b>c) errors.push(`${path}: idealSeconds no puede superar maxSeconds.`); if(a!=null&&c!=null&&a>c) errors.push(`${path}: minSeconds no puede superar maxSeconds.`); }
function requirements(v,errors){ if(!Array.isArray(v)) return errors.push("creativeRequirements: debe ser una lista."); if(v.length>THEORY_LIMITS.requirementCount) errors.push("creativeRequirements: demasiados requisitos."); const seen=new Set(); v.forEach((r,i)=>{ const p=`creativeRequirements[${i}]`; if(!r||typeof r!=="object"||Array.isArray(r)) return errors.push(`${p}: debe ser un objeto.`); const ex=extra(r,REQ); if(ex.length) errors.push(`${p}: claves desconocidas: ${ex.join(", ")}.`); key(r.key,`${p}.key`,errors); if(seen.has(r.key)) errors.push(`${p}.key: repetida.`); seen.add(r.key); text(r.label,`${p}.label`,errors,{required:true,max:160}); if(typeof r.required!=="boolean") errors.push(`${p}.required: debe ser booleano.`); for(const k of ["minCount","recommendedCount","maxCount"]){ if(!Number.isInteger(r[k])||r[k]<0||r[k]>THEORY_LIMITS.count) errors.push(`${p}.${k}: cantidad inválida.`); } if(Number.isInteger(r.minCount)&&Number.isInteger(r.recommendedCount)&&r.minCount>r.recommendedCount) errors.push(`${p}: minCount no puede superar recommendedCount.`); if(Number.isInteger(r.recommendedCount)&&Number.isInteger(r.maxCount)&&r.recommendedCount>r.maxCount) errors.push(`${p}: recommendedCount no puede superar maxCount.`); duration(r.duration,`${p}.duration`,errors); text(r.instructions,`${p}.instructions`,errors,{max:THEORY_LIMITS.instruction}); }); }
function validationRules(v,errors){ if(!Array.isArray(v)) return errors.push("validationRules: debe ser una lista."); if(v.length>THEORY_LIMITS.ruleCount) errors.push("validationRules: demasiadas reglas."); const seen=new Set(); v.forEach((r,i)=>{ const p=`validationRules[${i}]`; if(!r||typeof r!=="object"||Array.isArray(r)) return errors.push(`${p}: debe ser un objeto.`); const ex=extra(r,["key","label","severity","instructions"]); if(ex.length) errors.push(`${p}: claves desconocidas: ${ex.join(", ")}.`); key(r.key,`${p}.key`,errors); if(seen.has(r.key)) errors.push(`${p}.key: repetida.`); seen.add(r.key); text(r.label,`${p}.label`,errors,{required:true,max:160}); if(!["info","warning","error"].includes(r.severity)) errors.push(`${p}.severity: valor inválido.`); text(r.instructions,`${p}.instructions`,errors,{max:THEORY_LIMITS.instruction}); }); }

const rule=r=>({ key:str(r?.key,64), label:str(r?.label,160), instructions:str(r?.instructions,THEORY_LIMITS.instruction), appliesToObjectives:arr(r?.appliesToObjectives,30,80), appliesToPlatforms:arr(r?.appliesToPlatforms,20,80) });
export function sanitizeTheoryConfig(input={}){ return { schemaVersion:1, platform:str(input.platform||"meta_ads",64)||"meta_ads", name:str(input.name,THEORY_LIMITS.name), description:str(input.description,THEORY_LIMITS.description), campaignRules:(Array.isArray(input.campaignRules)?input.campaignRules:[]).slice(0,80).map(rule), creativeRequirements:(Array.isArray(input.creativeRequirements)?input.creativeRequirements:[]).slice(0,80).map(r=>({ key:str(r?.key,64), label:str(r?.label,160), required:r?.required===true, minCount:Number.isInteger(r?.minCount)?r.minCount:0, recommendedCount:Number.isInteger(r?.recommendedCount)?r.recommendedCount:0, maxCount:Number.isInteger(r?.maxCount)?r.maxCount:0, duration:{ minSeconds:typeof r?.duration?.minSeconds==="number"?r.duration.minSeconds:null, idealSeconds:typeof r?.duration?.idealSeconds==="number"?r.duration.idealSeconds:null, maxSeconds:typeof r?.duration?.maxSeconds==="number"?r.duration.maxSeconds:null }, instructions:str(r?.instructions,THEORY_LIMITS.instruction) })), validationRules:(Array.isArray(input.validationRules)?input.validationRules:[]).slice(0,80).map(r=>({ key:str(r?.key,64), label:str(r?.label,160), severity:["info","warning","error"].includes(r?.severity)?r.severity:"warning", instructions:str(r?.instructions,THEORY_LIMITS.instruction) })), questionPolicy:{ mode:["minimal","guided","custom"].includes(input?.questionPolicy?.mode)?input.questionPolicy.mode:"minimal", instructions:str(input?.questionPolicy?.instructions,THEORY_LIMITS.instruction), requiredFields:arr(input?.questionPolicy?.requiredFields,50,80) }, testingRules:(Array.isArray(input.testingRules)?input.testingRules:[]).slice(0,80).map(rule), recommendationRules:(Array.isArray(input.recommendationRules)?input.recommendationRules:[]).slice(0,80).map(rule), metadata:{ compilerNotes:str(input?.metadata?.compilerNotes,THEORY_LIMITS.description) } }; }
export function validateTheoryConfig(input){ const errors=[]; if(!input||typeof input!=="object"||Array.isArray(input)) return {valid:false,errors:["TheoryConfig debe ser un objeto."],value:null}; const ex=extra(input,TOP); if(ex.length) errors.push(`Claves desconocidas: ${ex.join(", ")}.`); if(input.schemaVersion!==1) errors.push("schemaVersion debe ser 1."); text(input.platform,"platform",errors,{required:true,max:64}); text(input.name,"name",errors,{required:true,max:THEORY_LIMITS.name}); text(input.description,"description",errors,{max:THEORY_LIMITS.description}); ruleList(input.campaignRules,"campaignRules",errors); requirements(input.creativeRequirements,errors); validationRules(input.validationRules,errors); const q=input.questionPolicy; if(!q||typeof q!=="object"||Array.isArray(q)) errors.push("questionPolicy: debe ser un objeto."); else { const qx=extra(q,["mode","instructions","requiredFields"]); if(qx.length) errors.push(`questionPolicy: claves desconocidas: ${qx.join(", ")}.`); if(!["minimal","guided","custom"].includes(q.mode)) errors.push("questionPolicy.mode: valor inválido."); text(q.instructions,"questionPolicy.instructions",errors,{max:THEORY_LIMITS.instruction}); stringList(q.requiredFields,"questionPolicy.requiredFields",errors,50,80); } ruleList(input.testingRules,"testingRules",errors); ruleList(input.recommendationRules,"recommendationRules",errors); if(!input.metadata||typeof input.metadata!=="object"||Array.isArray(input.metadata)) errors.push("metadata: debe ser un objeto."); else { const mx=extra(input.metadata,["compilerNotes"]); if(mx.length) errors.push(`metadata: claves desconocidas: ${mx.join(", ")}.`); text(input.metadata.compilerNotes,"metadata.compilerNotes",errors,{max:THEORY_LIMITS.description}); } const value=sanitizeTheoryConfig(input); if(DANGEROUS.test(JSON.stringify(value))) errors.push("TheoryConfig contiene contenido potencialmente peligroso."); return {valid:errors.length===0,errors,value:errors.length===0?value:null}; }
export function assertValidTheoryConfig(input){ const r=validateTheoryConfig(input); if(!r.valid){ const e=new Error(r.errors[0]||"TheoryConfig inválido."); e.code="theory-config-invalid"; e.validationErrors=r.errors; throw e; } return r.value; }
export function makeEmptyTheoryConfig(name=""){ return {schemaVersion:1,platform:"meta_ads",name:str(name,120),description:"",campaignRules:[],creativeRequirements:[],validationRules:[],questionPolicy:{mode:"minimal",instructions:"",requiredFields:[]},testingRules:[],recommendationRules:[],metadata:{compilerNotes:""}}; }

const s=(max,{nullable=false,min=0}={})=>nullable?{type:["string","null"],maxLength:max}:{type:"string",minLength:min,maxLength:max};
const ruleSchema={type:"object",additionalProperties:false,properties:{key:s(64,{min:1}),label:s(160,{min:1}),instructions:s(4000),appliesToObjectives:{type:"array",maxItems:30,items:s(80,{min:1})},appliesToPlatforms:{type:"array",maxItems:20,items:s(80,{min:1})}},required:RULE};
export const THEORY_CONFIG_JSON_SCHEMA=Object.freeze({type:"object",additionalProperties:false,properties:{schemaVersion:{type:"integer",enum:[1]},platform:s(64,{min:1}),name:s(120,{min:1}),description:s(4000),campaignRules:{type:"array",maxItems:80,items:ruleSchema},creativeRequirements:{type:"array",maxItems:80,items:{type:"object",additionalProperties:false,properties:{key:s(64,{min:1}),label:s(160,{min:1}),required:{type:"boolean"},minCount:{type:"integer",minimum:0,maximum:100},recommendedCount:{type:"integer",minimum:0,maximum:100},maxCount:{type:"integer",minimum:0,maximum:100},duration:{type:"object",additionalProperties:false,properties:{minSeconds:{type:["number","null"],minimum:0,maximum:900},idealSeconds:{type:["number","null"],minimum:0,maximum:900},maxSeconds:{type:["number","null"],minimum:0,maximum:900}},required:DUR},instructions:s(4000)},required:REQ}},validationRules:{type:"array",maxItems:80,items:{type:"object",additionalProperties:false,properties:{key:s(64,{min:1}),label:s(160,{min:1}),severity:{type:"string",enum:["info","warning","error"]},instructions:s(4000)},required:["key","label","severity","instructions"]}},questionPolicy:{type:"object",additionalProperties:false,properties:{mode:{type:"string",enum:["minimal","guided","custom"]},instructions:s(4000),requiredFields:{type:"array",maxItems:50,items:s(80,{min:1})}},required:["mode","instructions","requiredFields"]},testingRules:{type:"array",maxItems:80,items:ruleSchema},recommendationRules:{type:"array",maxItems:80,items:ruleSchema},metadata:{type:"object",additionalProperties:false,properties:{compilerNotes:s(4000)},required:["compilerNotes"]}},required:TOP});
