import test from 'node:test';
import assert from 'node:assert/strict';
import { createEcommerceOrder } from '../netlify/functions/_lib/ecommerce/commerceService.mjs';
import { confirmEcommercePayment } from '../netlify/functions/_lib/ecommerce/paymentService.mjs';
import { prepareEcommerceInvoiceFiscal, resolveEcommerceReceiver } from '../netlify/functions/_lib/ecommerce/fiscalService.mjs';
import { canRequestInvoiceForSale, ensurePendingInvoice, syncInvoiceToSale } from '../netlify/functions/_lib/arca/invoicePersistence.mjs';
import { customerDocumentId } from '../src/gestion/customers/customerDomain.js';

export const qaEnv = { NODE_ENV:'test', CONTEXT:'dev', ECOMMERCE_SIMULATED_PAYMENT_ENABLED:'true', ECOMMERCE_LOCATION_ID:'qa-local', ECOMMERCE_PICKUP_ENABLED:'true', ARCA_ENVIRONMENT:'homologation', ARCA_ISSUER_CUIT:'20123456786', ARCA_ISSUER_VAT_CONDITION:'responsable_inscripto', ARCA_POINT_OF_SALE:'3', ARCA_AUTO_AUTHORIZE_PRODUCTION_SOURCES:'admin_quick_sale', ARCA_ALLOW_PRODUCTION_CAE:'false' };
function store() {
  const records = new Map(); let revision=0;
  const put=(path,data)=>records.set(path,{path,data:structuredClone(data),updateTime:String(++revision)});
  put('locations/qa-local',{name:'QA ficticia',active:true});
  put('products/qa-product',{name:'Producto QA',active:true,defaultPrice:22000,arcaVatRate:21});
  put('locationStock/qa-local/items/qa-product',{productId:'qa-product',currentStock:5,priceMode:'default'});
  const getDocument=async path=>structuredClone(records.get(path)||null);
  const commitDocuments=async operations=>{
    for(const op of operations){const before=records.get(op.path); if(op.type==='create' && before)throw Object.assign(new Error('exists'),{code:'firebase-admin-already-exists'}); if(op.type==='update' && (!before || (op.currentUpdateTime && before.updateTime!==op.currentUpdateTime)))throw Object.assign(new Error('changed'),{code:'firebase-admin-precondition-failed'});}
    for(const op of operations) put(op.path,op.type==='create'?op.data:{...records.get(op.path).data,...op.data});
  };
  const createDocument=async(collection,id,data)=>{await commitDocuments([{type:'create',path:`${collection}/${id}`,data}]); return getDocument(`${collection}/${id}`);};
  const patchDocument=async(path,data,options={})=>{await commitDocuments([{type:'update',path,data,currentUpdateTime:options.currentUpdateTime}]);return getDocument(path);};
  return {records,put,getDocument,commitDocuments,createDocument,patchDocument};
}
const request=(key='qa_request_0001')=>({requestId:key,items:[{productId:'qa-product',quantity:2}],customer:{fullName:'Cliente QA',email:'qa@example.invalid',phone:'1112345678'},deliveryMethod:'pickup',paymentMode:'pending',clientTotal:1});
async function setup(){const db=store(); const body=request(); const result=await createEcommerceOrder({body,env:qaEnv,...db}); return {db,body,order:result.order};}
const approve=(s,extra={})=>confirmEcommercePayment({orderId:s.order.id,idempotencyKey:s.body.requestId,provider:'simulation',status:'approved',reference:'qa-payment-reference',actor:{uid:'qa-admin',role:'admin'},env:qaEnv,...s.db,...extra});
const fiscal=(s,extra={})=>prepareEcommerceInvoiceFiscal({orderId:s.order.id,idempotencyKey:s.body.requestId,requestedBy:'qa-admin',env:qaEnv,...s.db,ensureInvoiceFn:args=>ensurePendingInvoice({...args,createDocument:s.db.createDocument}),syncInvoiceFn:syncInvoiceToSale,...extra});
const count=(s,prefix)=>[...s.db.records.keys()].filter(p=>p.startsWith(prefix+'/')).length;
const rejectsCode=(fn,code)=>assert.rejects(fn,e=>e.code===code);

test('runtime CRM: pedido pendiente no crea cliente; aprobación concurrente asocia un maestro sin duplicar',async()=>{
  const s=await setup();assert.equal(count(s,'customers'),0);
  const [a,b]=await Promise.all([approve(s),approve(s)]);assert.equal(a.saleId,b.saleId);
  const id=await customerDocumentId(s.body.customer.phone), sale=(await s.db.getDocument(`sales/${a.saleId}`)).data;
  assert.equal(sale.customerId,id);assert.equal(sale.customerPhoneNormalized,'1112345678');assert.equal(count(s,'customers'),1);
  assert.equal((await s.db.getDocument(`customers/${id}`)).data.name,'Cliente QA');await approve(s);assert.equal(count(s,'customers'),1);
});
test('runtime CRM: ecommerce conserva nombre/zona existentes y completa sólo vacíos',async()=>{
  const s=await setup(),id=await customerDocumentId(s.body.customer.phone);
  s.db.put(`customers/${id}`,{phone:'+54 9 11 1234-5678',phoneNormalized:'1112345678',name:'Nombre del maestro',zoneName:'Zona del maestro',active:true});
  await approve(s);const customer=(await s.db.getDocument(`customers/${id}`)).data;
  assert.equal(customer.name,'Nombre del maestro');assert.equal(customer.zoneName,'Zona del maestro');assert.equal(customer.phone,'+54 9 11 1234-5678');assert.equal(count(s,'customers'),1);
});

test('runtime: checkout recalcula total; Order/Payment pending sin Sale ni stock descontado',async()=>{const s=await setup();assert.equal(s.order.total,44000);assert.equal(s.order.paymentStatus,'pending');assert.equal((await s.db.getDocument(`payments/${s.order.paymentId}`)).data.status,'pending');assert.equal(count(s,'sales'),0);assert.equal((await s.db.getDocument('locationStock/qa-local/items/qa-product')).data.currentStock,5);});
test('runtime: misma request/key devuelve misma Order; distinto contenido conflict',async()=>{const s=await setup();const repeated=await createEcommerceOrder({body:s.body,env:qaEnv,...s.db});assert.equal(repeated.order.id,s.order.id);assert.equal(repeated.idempotent,true);await rejectsCode(()=>createEcommerceOrder({body:{...s.body,items:[{productId:'qa-product',quantity:1}]},env:qaEnv,...s.db}),'ecommerce-idempotency-conflict');assert.equal(count(s,'orders'),1);});
test('runtime: checkout público rechaza simulate_approved también en replay',async()=>{const s=await setup();await rejectsCode(()=>createEcommerceOrder({body:{...s.body,paymentMode:'simulate_approved'},env:qaEnv,...s.db}),'ecommerce-checkout-payment-authority-denied');});
for(const [label,env,code] of [['flag off',{ECOMMERCE_SIMULATED_PAYMENT_ENABLED:'false'},'ecommerce-simulated-payment-disabled'],['production',{CONTEXT:'production',NETLIFY_DEV:'true'},'ecommerce-simulated-payment-local-only'],['deploy-preview',{CONTEXT:'deploy-preview',NETLIFY_DEV:'true'},'ecommerce-simulated-payment-local-only'],['branch-deploy',{CONTEXT:'branch-deploy',NETLIFY_DEV:'true'},'ecommerce-simulated-payment-local-only']])test(`runtime: ${label} bloquea sin escrituras`,async()=>{const s=await setup();await rejectsCode(()=>approve(s,{env:{...qaEnv,...env}}),code);assert.equal(count(s,'sales'),0);});
test('runtime: default off y una variable VITE no habilitan la simulación',async()=>{const s=await setup();const env={...qaEnv,VITE_ECOMMERCE_SIMULATED_PAYMENT_ENABLED:'true'};delete env.ECOMMERCE_SIMULATED_PAYMENT_ENABLED;await rejectsCode(()=>approve(s,{env}),'ecommerce-simulated-payment-disabled');assert.equal(count(s,'sales'),0);});
test('runtime: no admin bloqueado',async()=>{const s=await setup();await rejectsCode(()=>approve(s,{actor:{role:'seller'}}),'ecommerce-simulation-admin-required');assert.equal(count(s,'sales'),0);});
test('runtime: Payway rejected no crea Sale/Invoice ni descuenta stock',async()=>{const s=await setup();const r=await approve(s,{provider:'payway',status:'rejected'});assert.equal(r.paymentStatus,'rejected');assert.equal(count(s,'sales'),0);assert.equal(count(s,'invoices'),0);});
test('runtime: dos approvals concurrentes y retry crean una Sale, un descuento y una Invoice',async()=>{const s=await setup();const [a,b]=await Promise.all([approve(s),approve(s)]);assert.equal(a.saleId,b.saleId);assert.equal(a.paymentStatus,'simulated_approved');assert.equal(count(s,'sales'),1);assert.equal(count(s,'stockMovements'),1);assert.equal((await s.db.getDocument('locationStock/qa-local/items/qa-product')).data.currentStock,3);const [i,j]=await Promise.all([fiscal(s),fiscal(s)]);assert.equal(i.invoiceId,j.invoiceId);assert.equal(count(s,'invoices'),1);assert.equal(i.receiver.documentType,99);assert.equal(i.fiscal.voucherClass,'B');assert.equal(i.fiscal.total,44000);assert.equal(i.fiscal.transport,'blocked');assert.equal(i.fiscal.caeRequested,false);assert.equal((await s.db.getDocument(`invoices/${i.invoiceId}`)).data.authorization.cae,null);assert.equal((await approve(s)).idempotent,true);});
for(const [label,path,patch,code] of [['producto inexistente','products/qa-product',null,'ecommerce-product-not-found'],['producto inactivo','products/qa-product',{active:false},'ecommerce-product-inactive'],['precio inválido','products/qa-product',{defaultPrice:0},'ecommerce-price-not-configured'],['cambio de precio','products/qa-product',{defaultPrice:23000},'ecommerce-order-commercial-drift'],['stock insuficiente','locationStock/qa-local/items/qa-product',{currentStock:1},'ecommerce-stock-insufficient']])test(`runtime: aprobación rechaza ${label}`,async()=>{const s=await setup();if(patch===null)s.db.records.delete(path);else s.db.put(path,{...(await s.db.getDocument(path)).data,...patch});await rejectsCode(()=>approve(s),code);assert.equal(count(s,'sales'),0);});
test('runtime: payment amount inconsistente y key incorrecta bloqueadas',async()=>{const s=await setup();await rejectsCode(()=>approve(s,{idempotencyKey:'qa_wrong_key'}),'ecommerce-idempotency-conflict');const p=`payments/${s.order.paymentId}`;s.db.put(p,{...(await s.db.getDocument(p)).data,amount:1});await rejectsCode(()=>approve(s),'ecommerce-payment-amount-conflict');assert.equal(count(s,'sales'),0);});
test('runtime: Payment final incompatible no permite nueva aprobación',async()=>{const s=await setup();const p=`payments/${s.order.paymentId}`;s.db.put(p,{...(await s.db.getDocument(p)).data,status:'rejected'});await assert.rejects(()=>approve(s));assert.equal(count(s,'sales'),0);});
test('runtime: error fiscal tras Sale y retry conservan Sale/stock/Invoice',async()=>{const s=await setup();await approve(s);await rejectsCode(()=>fiscal(s,{env:{...qaEnv,ARCA_ISSUER_VAT_CONDITION:''}}),'arca-issuer-vat-condition-missing');const r=await fiscal(s);assert.equal(count(s,'sales'),1);assert.equal(count(s,'invoices'),1);assert.equal((await s.db.getDocument('locationStock/qa-local/items/qa-product')).data.currentStock,3);assert.equal(r.fiscal.caeRequested,false);});
test('runtime: CUIT mock produce plan A sin autorización ni CAE',async()=>{const s=await setup();await approve(s);const r=await fiscal(s,{receiverCuit:'20-12345678-6',getTaxpayerFn:async()=>({qa:true}),inferReceiverFn:()=>({resolved:true,condition:{id:1}})});assert.equal(r.receiver.documentType,80);assert.equal(r.fiscal.voucherClass,'A');assert.equal(r.fiscal.caeRequested,false);});
test('runtime: CUIT inválido no se convierte silenciosamente a Consumidor Final',async()=>{for(const cuit of ['basura',true,[],{}])await assert.rejects(()=>resolveEcommerceReceiver({cuit},{env:qaEnv}));});
test('runtime: umbral CF genera blocker de identificación',async()=>{const s=await setup();await approve(s);const r=await fiscal(s,{env:{...qaEnv,ARCA_CONSUMER_FINAL_ID_THRESHOLD:'44000'}});assert.ok(r.fiscal.blockers.length>0);assert.equal(r.fiscal.caeRequested,false);});
test('runtime: mockAuthorize sólo en test; ningún CAE inventado se persiste',async()=>{const s=await setup();await approve(s);let calls=0;const mockAuthorizeFn=async()=>{calls++;return {test:true};};await rejectsCode(()=>fiscal(s,{env:{...qaEnv,NODE_ENV:'development'},mockAuthorizeFn}),'ecommerce-mock-authorize-test-only');assert.equal(calls,0);const r=await fiscal(s,{mockAuthorizeFn});assert.equal(calls,1);assert.equal(r.fiscal.mode,'mock-authorize-test');assert.equal((await s.db.getDocument(`invoices/${r.invoiceId}`)).data.authorization.cae,null);});
test('runtime: replay fiscal no puede cambiar receptor de Invoice existente',async()=>{const s=await setup();await approve(s);await fiscal(s);await assert.rejects(()=>fiscal(s,{receiverCuit:'20123456786',getTaxpayerFn:async()=>({}),inferReceiverFn:()=>({resolved:true,condition:{id:1}})}));assert.equal(count(s,'invoices'),1);});
test('runtime: identidades de documentos no se toman del campo id',async()=>{const s=await setup();s.db.put(`orders/${s.order.id}`,{...s.order,id:'forged-order'});const r=await approve(s);assert.equal(r.order.id,s.order.id);});
test('runtime: dos checkouts concurrentes con igual key y distinto contenido dan conflict',async()=>{const db=store();const a=request('qa_checkout_race');const b={...a,items:[{productId:'qa-product',quantity:1}]};const results=await Promise.allSettled([createEcommerceOrder({body:a,env:qaEnv,...db}),createEcommerceOrder({body:b,env:qaEnv,...db})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'ecommerce-idempotency-conflict');assert.equal([...db.records.keys()].filter(p=>p.startsWith('orders/')).length,1);});
test('runtime: dos Orders concurrentes no venden más stock del disponible',async()=>{const db=store();const a=request('qa_stock_race_a'),b=request('qa_stock_race_b');a.items[0].quantity=4;b.items[0].quantity=4;const oa=await createEcommerceOrder({body:a,env:qaEnv,...db}),ob=await createEcommerceOrder({body:b,env:qaEnv,...db});const results=await Promise.allSettled([approve({db,body:a,order:oa.order}),approve({db,body:b,order:ob.order})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal([...db.records.keys()].filter(p=>p.startsWith('sales/')).length,1);assert.equal((await db.getDocument('locationStock/qa-local/items/qa-product')).data.currentStock,1);});
test('runtime: booleans/arrays no representan precios, cantidades ni stock válidos',async()=>{for(const invalid of [true,[],[22000],{}]){const s=await setup();s.db.put('products/qa-product',{...(await s.db.getDocument('products/qa-product')).data,defaultPrice:invalid});await rejectsCode(()=>approve(s),'ecommerce-price-not-configured');}for(const quantity of [true,[1],{}]){const db=store();await rejectsCode(()=>createEcommerceOrder({body:{...request(),items:[{productId:'qa-product',quantity}]},env:qaEnv,...db}),'ecommerce-quantity-invalid');}});
test('runtime: key malformada no se normaliza a una identidad existente',async()=>{const s=await setup();await rejectsCode(()=>approve(s,{idempotencyKey:'qa_request_0001!'}),'ecommerce-request-id-invalid');});
test('runtime: stock movements para IDs a.b y a_b no colisionan',async()=>{const db=store();for(const id of ['a.b','a_b']){db.put(`products/${id}`,{name:id,active:true,defaultPrice:22000,arcaVatRate:21});db.put(`locationStock/qa-local/items/${id}`,{productId:id,currentStock:2,priceMode:'default'});}const body={...request('qa_product_collision'),items:[{productId:'a.b',quantity:1},{productId:'a_b',quantity:1}]};const {order}=await createEcommerceOrder({body,env:qaEnv,...db});await approve({db,body,order});assert.equal([...db.records.keys()].filter(p=>p.startsWith('stockMovements/')).length,2);});
test('runtime: reintento fiscal conserva IVA confirmado aunque cambie el master',async()=>{const s=await setup();await approve(s);s.db.put('products/qa-product',{name:'master changed',defaultPrice:99999,arcaVatRate:27});const r=await fiscal(s);const i=await s.db.getDocument(`invoices/${r.invoiceId}`);assert.equal(i.data.productFiscalSnapshot[0].arcaVatRate,21);assert.equal(r.fiscal.total,44000);});
test('runtime: invoice determinística no enmascara otra asociación fiscal',async()=>{const s=await setup();await approve(s);await fiscal(s);const salePath=`sales/ecommerce_sale_${s.body.requestId}`;s.db.put(salePath,{...(await s.db.getDocument(salePath)).data,fiscalInvoiceId:'different-invoice'});await rejectsCode(()=>fiscal(s),'arca-sale-invoice-conflict');assert.equal(count(s,'invoices'),1);});
test('runtime: proveedor o moneda inconsistentes bloquean preparación fiscal',async()=>{for(const patch of [{provider:'payway'},{currency:'USD'}]){const s=await setup();await approve(s);const p=`payments/${s.order.paymentId}`;s.db.put(p,{...(await s.db.getDocument(p)).data,...patch});await rejectsCode(()=>fiscal(s),'ecommerce-payment-not-approved');assert.equal(count(s,'invoices'),0);}});
test('runtime: Ecommerce no se enmascara como admin_quick_sale para entrar en allowlist productiva',async()=>{const s=await setup();await approve(s);const sourceId=`ecommerce_sale_${s.body.requestId}`;const sale=(await s.db.getDocument(`sales/${sourceId}`)).data;assert.equal(canRequestInvoiceForSale({sourceType:'admin_quick_sale',sale,session:{profile:{role:'admin'}}}),false);await rejectsCode(()=>ensurePendingInvoice({sourceType:'admin_quick_sale',sourceId,env:qaEnv,...s.db}),'arca-sale-source-mismatch');assert.equal(count(s,'invoices'),0);});
