import test from "node:test";
import assert from "node:assert/strict";
import { THEORY_CONFIG_SCHEMA_VERSION, assertValidTheoryConfig, makeEmptyTheoryConfig, validateTheoryConfig } from "../src/gestion/marketing/metaAds/theorySchema.js";
import { canActivateTheoryVersion, canCreateNextTheoryVersion, canEditTheoryVersion, nextTheoryVersionNumber, normalizeTheorySource, theoryVersionId, validateVersionTransition } from "../src/gestion/marketing/metaAds/theoryDomain.js";
import { can, canAccessManagementRoute } from "../src/gestion/permissions.js";
function validConfig(){return {...makeEmptyTheoryConfig("Método"),creativeRequirements:[{key:"hook",label:"Hooks",required:true,minCount:1,recommendedCount:3,maxCount:6,duration:{minSeconds:3,idealSeconds:4.5,maxSeconds:6},instructions:"Abrir con una idea clara."},{key:"testimonial",label:"Testimonial",required:false,minCount:0,recommendedCount:1,maxCount:3,duration:{minSeconds:null,idealSeconds:null,maxSeconds:null},instructions:"Categoría dinámica sin cambios de código."}]};}
test("TheoryConfig válido conserva schemaVersion y categorías dinámicas",()=>{const r=validateTheoryConfig(validConfig());assert.equal(r.valid,true,r.errors.join("\n"));assert.equal(r.value.schemaVersion,THEORY_CONFIG_SCHEMA_VERSION);assert.equal(r.value.creativeRequirements[1].key,"testimonial");});
test("TheoryConfig rechaza cantidad negativa y min mayor que max",()=>{const c=validConfig();c.creativeRequirements[0].minCount=-1;c.creativeRequirements[0].recommendedCount=8;c.creativeRequirements[0].maxCount=2;const r=validateTheoryConfig(c);assert.equal(r.valid,false);assert.match(r.errors.join(" "),/minCount|recommendedCount/);});
test("TheoryConfig rechaza duración inválida y claves desconocidas",()=>{const c=validConfig();c.creativeRequirements[0].duration={minSeconds:7,idealSeconds:5,maxSeconds:4};c.rootkit="no";const r=validateTheoryConfig(c);assert.equal(r.valid,false);assert.match(r.errors.join(" "),/duración|min|max|Claves desconocidas/i);});
test("TheoryConfig rechaza schemaVersion incorrecto y contenido peligroso",()=>{const c=validConfig();c.schemaVersion=99;c.description="<script>alert(1)</script>";assert.equal(validateTheoryConfig(c).valid,false);assert.throws(()=>assertValidTheoryConfig(c));});
test("la teoría admite cambiar recommendedCount 3 a 6 sin cambiar código",()=>{const a=validConfig(),b=structuredClone(a);b.creativeRequirements[0].recommendedCount=6;b.creativeRequirements[0].maxCount=8;assert.equal(validateTheoryConfig(a).valid,true);assert.equal(validateTheoryConfig(b).valid,true);});
test("normalización de fuente limita tipos y tamaño",()=>{const s=normalizeTheorySource({sourceType:"markdown",sourceName:"metodo.md",sourceText:"# Teoría\nContenido",sourceSize:20,sourceHash:"abc"});assert.equal(s.metadata.sourceType,"markdown");assert.equal(s.metadata.sourceCharacterCount,s.text.length);assert.throws(()=>normalizeTheorySource({sourceType:"exe",sourceText:"x"}));assert.throws(()=>normalizeTheorySource({sourceType:"text",sourceText:""}));});
test("transiciones e inmutabilidad de versión son explícitas",()=>{assert.equal(validateVersionTransition("draft","compiling"),true);assert.equal(validateVersionTransition("compiling","review"),true);assert.equal(validateVersionTransition("review","approved"),true);assert.equal(validateVersionTransition("approved","active"),true);assert.equal(validateVersionTransition("active","review"),false);assert.equal(validateVersionTransition("active","archived"),true);assert.equal(validateVersionTransition("archived","active"),true);assert.equal(canEditTheoryVersion({status:"active"}),false);assert.equal(canEditTheoryVersion({status:"review"}),true);assert.equal(canCreateNextTheoryVersion({status:"active"}),true);assert.equal(canActivateTheoryVersion({status:"archived"}),true);});
test("versiones tienen numeración determinística",()=>{assert.equal(theoryVersionId(1),"v1");assert.equal(theoryVersionId(12),"v12");assert.equal(nextTheoryVersionNumber({latestVersion:3}),4);assert.throws(()=>theoryVersionId(0));});
test("roles Meta Ads permiten a admin y marketing, y niegan al seller incluso por ruta",()=>{const admin={id:"admin",active:true,role:"admin"};const marketing={id:"marketing",active:true,role:"marketing_manager"};const seller={id:"seller",active:true,role:"seller"};for(const profile of [admin,marketing]){assert.equal(can(profile,"marketing","metaAdsView"),true);assert.equal(can(profile,"marketing","metaAdsManageKnowledge"),true);assert.equal(can(profile,"marketing","metaAdsManageTheory"),true);assert.equal(canAccessManagementRoute(profile,"marketing"),true);}for(const action of ["metaAdsView","metaAdsManageKnowledge","metaAdsManageTheory"])assert.equal(can(seller,"marketing",action),false);assert.equal(canAccessManagementRoute(seller,"marketing"),false);});
