import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("hub Meta Ads conserva Campañas y agrega Conocimiento y Metodologías",async()=>{const s=await read("src/gestion/pages/MetaAdsHubPage.jsx");assert.match(s,/Campañas/);assert.match(s,/Conocimiento/);assert.match(s,/Metodologías/);assert.match(s,/MetaAdsPage/);assert.match(s,/MetaAdsKnowledgeView/);assert.match(s,/MetaAdsTheoriesView/);});
test("Theory UI exige procesamiento explícito, revisión, aprobación y activación",async()=>{const s=await read("src/gestion/pages/MetaAdsTheoriesView.jsx");assert.match(s,/Procesar con IA/);assert.match(s,/Preview estructurado/);assert.match(s,/Aprobar/);assert.match(s,/Activar/);assert.match(s,/Crear nueva versión/);assert.match(s,/OPENAI_API_KEY/);assert.match(s,/import\("\.\.\/marketing\/metaAds\/pdfTextExtractor"\)/);});
test("PDF se extrae lazy en navegador y no se persiste como binario",async()=>{const s=await read("src/gestion/marketing/metaAds/pdfTextExtractor.js");assert.match(s,/Este PDF no contiene texto extraíble/);assert.match(s,/arrayBuffer/);assert.doesNotMatch(s,/firebase\/storage/);assert.doesNotMatch(s,/setDoc|addDoc|writeBatch/);});
test("backend OpenAI usa Responses API, structured outputs y auth Firebase",async()=>{const [c,a]=await Promise.all([read("netlify/functions/theory-compiler.mjs"),read("netlify/functions/_lib/firebaseAuth.mjs")]);assert.match(c,/api\.openai\.com\/v1\/responses/);assert.match(c,/json_schema/);assert.match(c,/strict:true|strict:\s*true/);assert.match(c,/OPENAI_API_KEY/);assert.doesNotMatch(c,/VITE_OPENAI/);assert.match(a,/accounts:lookup/);assert.match(a,/app-integral-fm/);assert.match(c,/metaAdsManageTheory/);});
test("Knowledge UI reutiliza products y declara minimización de PII",async()=>{const [ui,service]=await Promise.all([read("src/gestion/pages/MetaAdsKnowledgeView.jsx"),read("src/gestion/marketing/metaAds/knowledgeService.js")]);assert.match(ui,/catálogo maestro/);assert.match(ui,/teléfonos, DNI, direcciones/);assert.match(service,/listMasterProductsShared/);assert.match(service,/marketingProductProfiles/);assert.doesNotMatch(service,/metaProducts/);});
