import test from 'node:test';
import assert from 'node:assert/strict';
const seller={id:'seller',name:'Vendedor QA',role:'seller',active:true,allowedLocationIds:['origin']};
const panel=await (await import('node:fs/promises')).readFile('src/gestion/seller/SellerPanel.jsx','utf8');
const handler=panel.slice(panel.indexOf('async (options = {}) => {',panel.indexOf('const submitSale =')),panel.indexOf('}, [submitState.busy',panel.indexOf('const submitSale ='))+1);
function panelHarness(extra={}){const calls=[],states=[];const noop=()=>{};const context={receiverVatConditionId:'5',receiverDocument:'',submitRef:{current:false},submitState:{busy:false},selectedLocation:{id:'origin'},currentItems:[{id:'oil',qty:1}],paymentMethod:'cash',payments:[],summary:{total:2500},selectedCustomer:null,ticketAllowed:true,online:true,editSale:null,profile:seller,appliedDiscounts:[],PAYMENT_LABELS:{cash:'Efectivo'},setSubmitState:s=>states.push(s),savePending:async s=>calls.push({offline:s}),createSellerSale:async s=>{calls.push(s);return{id:'sale-qa',saleCode:'QA',total:2500}},updateSellerSale:async()=>{},resetSale:noop,dailySales:{refresh:async()=>[]},setReceipt:noop,paymentAllocationSummary:()=>({}),formatMoney:String,...extra};const submit=Function(...Object.keys(context),'return ('+handler+');')(...Object.values(context));return{submit,calls,states};}
test('modal vendedor construye los cuatro receivers',async()=>{for(const vat of [5,1,6,4]){const h=panelHarness({receiverVatConditionId:String(vat),receiverDocument:vat===5?'':'20123456786'});await h.submit({requestInvoice:true});assert.deepEqual(h.calls[0].invoiceReceiver,{vatConditionId:vat,documentType:vat===5?99:80,documentNumber:vat===5?'0':'20123456786',anonymousConsumerFinal:vat===5,concept:1});}});
test('CUIT corto rechaza antes de registrar venta',async()=>{for(const vat of [1,6,4]){const h=panelHarness({receiverVatConditionId:String(vat),receiverDocument:'1234'});await h.submit({requestInvoice:true});assert.equal(h.calls.length,0);assert.match(h.states.at(-1).message,/11 dígitos/);}});
test('offline no registra venta remota y entrega receiver al guardado local',async()=>{const h=panelHarness({online:false,receiverVatConditionId:'6',receiverDocument:'20123456786'});await h.submit({requestInvoice:true});assert.equal(h.calls.length,1);assert.equal(h.calls[0].offline.invoiceReceiver.vatConditionId,6);});
