import { useMemo, useState } from "react";
import { Badge, Button, DataTable, EmptyState, FormField, Modal, PageHeader, Panel, Skeleton, StatCard, Tabs, Toast } from "../../design-system";
import { useAuth } from "../AuthContext";
import { useAsyncData } from "../hooks";
import { can } from "../permissions";
import { formatDateTime, formatMoney } from "../formatters";
import { buildMetricsDateRange } from "../../modules/locations/domain/metrics";
import { argentinaDateKey, argentinaMonthKey } from "../../modules/locations/domain/time";
import { PAYMENT_OPTIONS } from "../../modules/locations/domain/payments";
import { saleDate } from "../../modules/locations/domain/saleFacts";
import { saleChannelLabel } from "../../modules/locations/domain/channels";
import { listSalesByRange } from "../services/dashboardService";
import { listLocationsShared } from "../services/sharedResources";
import { EXPENSE_CATEGORIES, financeSummary } from "../finance/financeDomain";
import { cancelFinancialEntry, getFinanceConfig, listFinancialEntries, listLegacyFinancialEntries, newFinancialIntent, recordSettlement, resolveFinanceAlert, saveBudget, saveFinanceConfig, saveFinancialEntry, syncFinanceAlerts } from "../finance/financeService";

const blankEntry = () => ({ type: "expense", name: "", amount: "", category: "", nature: "variable", scope: "general", locationId: "", accruedOn: argentinaDateKey(), dueOn: "", paidOn: "", cashAccount: "", notes: "", reference: "", supplierId: "", orderId: "", shipmentId: "" });
const amountLabel = value => value == null ? "Sin datos suficientes" : formatMoney(value);
const invoiceLabel = sale => ({ authorized: "Autorizado", pending: "Pendiente", rejected: "Rechazado", blocked: "Requiere revisión", not_requested: "No solicitado" })[sale.fiscalInvoice?.status || sale.invoiceStatus] || (sale.fiscalInvoiceId ? "Comprobante asociado" : "No solicitado");

export default function FinancePage() {
  const { profile } = useAuth();
  const [month, setMonth] = useState(argentinaMonthKey()), [locationId, setLocationId] = useState(""), [tab, setTab] = useState("overview");
  const range = useMemo(() => buildMetricsDateRange("month", month), [month]);
  const locations = useAsyncData(() => listLocationsShared(profile), [profile.id]);
  const result = useAsyncData(async () => {
    const [sales, config, legacy] = await Promise.all([listSalesByRange({ profile, start: range.start, end: range.end, includeCancelled: true, useCache: false, locationIds: locationId ? [locationId] : undefined }), getFinanceConfig(profile), listLegacyFinancialEntries(profile)]);
    const entries = await listFinancialEntries(profile, range, sales.map(sale => sale.id));
    return { sales, entries, config, legacy };
  }, [profile.id, month, locationId]);
  const summary = useMemo(() => result.data ? financeSummary(result.data.sales, result.data.entries, result.data.config, range, locationId ? [locationId] : []) : null, [result.data, range, locationId]);
  const [form, setForm] = useState(blankEntry), [entryOpen, setEntryOpen] = useState(false), [intent, setIntent] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [budget, setBudget] = useState({ category: "", amount: "", threshold: "", locationId: "" });
  const [configForm, setConfigForm] = useState(null), [settlement, setSettlement] = useState(null), [settlementForm, setSettlementForm] = useState({ amount: "", paidOn: "", reference: "" });
  const [resolution, setResolution] = useState(null), [reason, setReason] = useState("");
  const canCreate = can(profile, "finance", "create"), canEdit = can(profile, "finance", "edit"), canConfigure = can(profile, "finance", "admin");
  const config = result.data?.config || { versions: [] };
  const latest = config.versions.at(-1);
  const categories = latest?.categories || EXPENSE_CATEGORIES;
  const methodMap = new Map();
  PAYMENT_OPTIONS.filter(option => option.value !== "multiple").forEach(option => methodMap.set(option.value, option.label));
  (summary?.settlements || []).forEach(part => methodMap.set(part.method, part.label));
  const methods = [...methodMap.entries()];
  const policy = configForm || { effectiveFrom: "", fees: latest?.fees || {}, taxPercent: latest?.taxPercent ?? "", categories };
  const act = async (operation, refreshOnly = false) => {
    setBusy(true); setMessage(""); let saved = false;
    try {
      await operation(); saved = !refreshOnly;
      const fresh = await result.refresh();
      if (canEdit) await syncFinanceAlerts(profile, financeSummary(fresh.sales, fresh.entries, fresh.config, range, locationId ? [locationId] : []));
      setMessage(refreshOnly ? "Datos y controles actualizados." : "Operación guardada y auditada.");
    } catch (error) {
      setMessage(saved ? `Error al actualizar datos o controles: ${error.message}. La operación ya quedó guardada; usá Actualizar para revisar su estado.` : `Error: ${error.message}`);
    } finally { setBusy(false); }
  };
  const field = (key, label, type = "text", optional = true) => <FormField label={label} required={!optional}><input type={type} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} value={form[key]} onChange={event => setForm(current => ({ ...current, [key]: event.target.value }))} /></FormField>;
  const locationOptions = (locations.data || []).filter(location => !location.deleted);

  return <div className="fm-page fm-finance-page">
    <PageHeader eyebrow="Administración financiera" title="Finanzas" description="Ingresos de ventas, gastos y acreditaciones trazables. Una venta representa un único ingreso económico." actions={canCreate ? <Button icon="Plus" onClick={() => { setForm(blankEntry()); setIntent(newFinancialIntent()); setEntryOpen(true); }}>Registrar movimiento</Button> : null} />
    <Panel title="Período y alcance"><div className="fm-crm-filters"><FormField label="Mes"><input type="month" value={month} onChange={event => { if (event.target.value) setMonth(event.target.value); }} /></FormField><FormField label="Ubicación"><select value={locationId} onChange={event => setLocationId(event.target.value)}><option value="">Todo el negocio</option>{locationOptions.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></FormField><Button variant="secondary" loading={busy} onClick={() => act(async () => {}, true)}>Actualizar {canEdit ? "y evaluar controles" : "datos"}</Button></div><p>Los gastos generales se muestran sin repartirlos artificialmente entre ubicaciones. El período económico usa devengamiento; caja utiliza fecha efectiva de pago.</p></Panel>
    <Tabs active={tab} onChange={setTab} tabs={[{ id: "overview", label: "Resumen" }, { id: "income", label: "Ventas e ingresos" }, { id: "expenses", label: "Gastos" }, { id: "cash", label: "Caja y acreditaciones" }, { id: "budgets", label: "Presupuestos" }, ...(canConfigure ? [{ id: "config", label: "Configuración" }] : [])]} />
    {message ? <Toast tone={message.startsWith("Error") ? "error" : "success"}>{message}</Toast> : null}
    {result.status === "loading" ? <Skeleton lines={6} /> : null}
    {result.status === "error" ? <Toast tone="error">No se pudo cargar Finanzas: {result.error.message}</Toast> : null}
    {locations.status === "error" ? <Toast tone="error">{locations.error.message}</Toast> : null}
    {summary && result.status === "ready" ? <>
      {tab === "overview" ? <>
        <section className="fm-stat-grid"><StatCard label="Ventas válidas" value={formatMoney(summary.saleIncome)} hint={`${summary.salesCount} ventas · sin sumar facturas`} icon="ReceiptText" /><StatCard label="Otros ingresos" value={formatMoney(summary.extraIncome)} hint="Registros externos trazables" icon="CircleDollarSign" /><StatCard label="Gastos devengados" value={formatMoney(summary.expenseTotal)} icon="Wallet" /><StatCard label="Margen de contribución" value={amountLabel(summary.contribution)} hint="Ventas − mercadería − comisiones − impuestos estimados" icon="ChartNoAxesCombined" /><StatCard label="Resultado estimado" value={amountLabel(summary.result)} hint="Contribución + ingresos externos − gastos" icon="ChartNoAxesCombined" /></section>
        <Panel title="Disponibilidad de costos"><p>Costo conocido de mercadería: {formatMoney(summary.knownCost)}. {summary.missingCost} unidades sin costo histórico. Comisiones: {amountLabel(summary.commissions)}. Impuestos estimados: {amountLabel(summary.taxes)}.</p><p>Se utilizan costos explícitos guardados en la venta y parámetros vigentes a su fecha. La fuente y valoración definitiva de costos está pendiente; los datos faltantes impiden estimar el margen.</p>{summary.inventoryTreatmentPending ? <p>Hay compras de mercadería devengadas. Su imputación al resultado está pendiente de definir: se mantienen en egresos y caja, y el resultado queda sin estimar para evitar descontar inventario dos veces.</p> : null}<p>Envíos cobrados al cliente: {formatMoney(summary.shippingCharged)} (ya incluidos en ventas). Los costos logísticos reales se registran como gastos vinculados; no se deducen del importe cobrado por enviar.</p></Panel>
        {result.data.legacy.length ? <Panel title="Registros anteriores por clasificar"><p>{result.data.legacy.length} registros genéricos recientes sin estructura económica. Se preservan y no se inventan importes.</p><DataTable rows={result.data.legacy} columns={[{ key: "name", label: "Registro" }, { key: "notes", label: "Observaciones" }]} /></Panel> : null}
      </> : null}
      {tab === "income" ? <><Panel title="Ingresos derivados de ventas" description="Incluye Panel Vendedor, Venta Rápida y ecommerce. Las anulaciones se reflejan al actualizar; generar factura no agrega otro ingreso."><DataTable rows={summary.sales} columns={[{ key: "saleCode", label: "Venta" }, { key: "date", label: "Fecha", render: sale => formatDateTime(saleDate(sale)) }, { key: "channel", label: "Canal", render: sale => saleChannelLabel(sale.sourceChannel) }, { key: "location", label: "Origen", render: sale => sale.stockOriginName || sale.locationName || sale.warehouseName }, { key: "total", label: "Importe", render: sale => formatMoney(sale.total) }, { key: "fiscal", label: "Comprobante", render: invoiceLabel }]} empty={<EmptyState title="Sin ventas válidas en este período" />} /></Panel><Panel title="Otros ingresos"><DataTable rows={summary.extraIncomeEntries} columns={[{ key: "name", label: "Concepto" }, { key: "reference", label: "Referencia" }, { key: "amount", label: "Importe", render: entry => formatMoney(entry.amount) }]} empty={<EmptyState title="Sin ingresos externos" />} /></Panel></> : null}
      {tab === "expenses" ? <Panel title="Gastos del período"><DataTable rows={summary.expenseHistory} columns={[{ key: "name", label: "Concepto" }, { key: "category", label: "Categoría" }, { key: "nature", label: "Naturaleza", render: entry => ({ fixed: "Fijo", variable: "Variable", extraordinary: "Extraordinario" })[entry.nature] }, { key: "location", label: "Alcance", render: entry => entry.scope === "general" ? "General" : locationOptions.find(location => location.id === entry.locationId)?.name || entry.locationId }, { key: "accruedOn", label: "Devengamiento" }, { key: "paidOn", label: "Pago efectivo" }, { key: "status", label: "Estado", render: entry => entry.status === "cancelled" || entry.deleted ? "Anulado · excluido del resultado" : "Activo" }, { key: "amount", label: "Importe", render: entry => formatMoney(entry.amount) }, { key: "action", label: "Acciones", render: entry => canEdit && entry.status !== "cancelled" && !entry.deleted ? <Button variant="secondary" onClick={() => { setReason(""); setResolution({ entry, type: "cancel" }); }}>Anular</Button> : null }]} empty={<EmptyState title="Sin gastos devengados en este período" />} /></Panel> : null}
      {tab === "cash" ? <>
        <section className="fm-stat-grid"><StatCard label="Movimiento de efectivo" value={formatMoney(summary.cashMovement)} hint="Ventas en efectivo y pagos efectivos registrados" icon="Wallet" /><StatCard label="Movimiento bancario registrado" value={formatMoney(summary.bankMovement)} hint="Acreditaciones con referencia y pagos registrados" icon="Landmark" /></section><p>Estos movimientos no representan el saldo de una cuenta: no hay saldo inicial ni conexión bancaria. El efectivo se mantiene separado de acreditaciones electrónicas.</p>
        <Panel title="Acreditaciones" description="Los plazos son días corridos configurados. Sin evidencia no se marca dinero como acreditado; dentro del plazo no se genera una alerta."><DataTable rows={summary.settlements} columns={[{ key: "saleCode", label: "Venta" }, { key: "label", label: "Medio" }, { key: "expected", label: "Neto esperado", render: part => amountLabel(part.expected) }, { key: "due", label: "Plazo", render: part => part.due ? formatDateTime(part.due) : "Sin configurar" }, { key: "actual", label: "Acreditado", render: part => part.actual ? formatMoney(part.actual.amount) : "Sin evidencia" }, { key: "state", label: "Estado", render: part => <Badge tone={part.discrepancy ? "error" : "neutral"}>{part.state}</Badge> }, { key: "action", label: "Acciones", render: part => canEdit ? <div className="fm-dialog-actions"><Button variant="secondary" onClick={() => { setSettlement(part); setSettlementForm({ amount: part.actual?.amount ?? "", paidOn: part.actual?.paidOn || argentinaDateKey(), reference: part.actual?.reference || "" }); }}>Registrar evidencia</Button>{part.discrepancy ? <Button variant="secondary" onClick={() => { setReason(""); setResolution({ part, type: "resolve" }); }}>Resolver con motivo</Button> : null}</div> : null }]} empty={<EmptyState title="Sin pagos electrónicos para controlar" />} /></Panel>
        <Panel title="Flujo proyectado" description="Sólo compromisos con vencimiento y acreditaciones con importe/plazo configurado. La integración bancaria y las proyecciones estadísticas están pendientes."><DataTable rows={summary.projected} columns={[{ key: "date", label: "Fecha prevista" }, { key: "name", label: "Concepto" }, { key: "amount", label: "Movimiento", render: row => formatMoney(row.amount) }, { key: "evidence", label: "Base de la proyección" }]} empty={<EmptyState title="Sin compromisos futuros respaldados por datos" />} /></Panel>
      </> : null}
      {tab === "budgets" ? <Panel title="Presupuestos mensuales" description="Comparación de presupuesto y gastos devengados por categoría. Las alertas utilizan el módulo existente.">
        <DataTable rows={summary.budgets} columns={[{ key: "category", label: "Categoría" }, { key: "amount", label: "Presupuesto", render: row => formatMoney(row.amount) }, { key: "spent", label: "Gastado", render: row => formatMoney(row.spent) }, { key: "difference", label: "Disponible", render: row => formatMoney(row.difference) }, { key: "percentage", label: "Consumo", render: row => `${row.percentage?.toFixed(1)} %` }, { key: "threshold", label: "Umbral", render: row => `${row.threshold} %` }]} empty={<EmptyState title="Sin presupuestos configurados" />} />
        {canEdit ? <div className="fm-crm-filters"><FormField label="Categoría"><select value={budget.category} onChange={event => setBudget({ ...budget, category: event.target.value })}><option value="">Elegir</option>{categories.map(category => <option key={category}>{category}</option>)}</select></FormField><FormField label="Presupuesto"><input type="number" min="0" value={budget.amount} onChange={event => setBudget({ ...budget, amount: event.target.value })} /></FormField><FormField label="Alertar al alcanzar (%)"><input type="number" min="1" max="100" value={budget.threshold} onChange={event => setBudget({ ...budget, threshold: event.target.value })} /></FormField><FormField label="Alcance"><select value={budget.locationId} onChange={event => setBudget({ ...budget, locationId: event.target.value })}><option value="">Todo el negocio</option>{locationOptions.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></FormField><Button loading={busy} onClick={() => act(() => saveBudget(profile, { ...budget, month }))}>Guardar presupuesto</Button></div> : null}
      </Panel> : null}
      {tab === "config" && canConfigure ? <Panel title="Parámetros financieros" description="Cada cambio conserva versión y vigencia. Vacío significa desconocido; cero significa una tasa explícita de cero. Son estimaciones internas, sin modificar la factura fiscal.">
        <div className="fm-crm-filters"><FormField label="Vigente desde" required><input type="date" value={policy.effectiveFrom} onChange={event => setConfigForm({ ...policy, effectiveFrom: event.target.value })} /></FormField><FormField label="Impuesto directo estimado (%)"><input type="number" min="0" max="100" step="0.01" value={policy.taxPercent} onChange={event => setConfigForm({ ...policy, taxPercent: event.target.value })} /></FormField></div>
        {methods.map(([method, label]) => <div key={method} className="fm-crm-filters"><strong>{label}</strong><FormField label={`Comisión ${label} (%)`}><input type="number" min="0" max="100" step="0.01" value={policy.fees[method]?.percent ?? ""} onChange={event => setConfigForm({ ...policy, fees: { ...policy.fees, [method]: { ...policy.fees[method], percent: event.target.value } } })} /></FormField>{method !== "cash" ? <FormField label={`Acreditación ${label} (días corridos)`}><input type="number" min="0" max="365" value={policy.fees[method]?.settlementDays ?? ""} onChange={event => setConfigForm({ ...policy, fees: { ...policy.fees, [method]: { ...policy.fees[method], settlementDays: event.target.value } } })} /></FormField> : null}</div>)}
        <FormField label="Categorías de gasto (una por línea)"><textarea rows={6} value={policy.categories.join("\n")} onChange={event => setConfigForm({ ...policy, categories: event.target.value.split("\n") })} /></FormField><Button loading={busy} onClick={() => act(async () => { await saveFinanceConfig(profile, policy); setConfigForm(null); })}>Guardar nueva versión</Button>
        <p>{config.versions.length} versión(es) conservada(s). La definición contable definitiva de impuestos, conciliación bancaria y valoración de costos permanece pendiente.</p>
      </Panel> : null}
    </> : null}
    <Modal open={entryOpen} onClose={() => !busy && setEntryOpen(false)} title="Registrar movimiento externo" description="Las ventas ya alimentan ingresos automáticamente." footer={<div className="fm-dialog-actions"><Button variant="secondary" disabled={busy} onClick={() => setEntryOpen(false)}>Cancelar</Button><Button loading={busy} onClick={() => act(async () => { await saveFinancialEntry(profile, form, intent); setEntryOpen(false); })}>Guardar movimiento</Button></div>}>
      <div className="fm-crm-filters"><FormField label="Tipo"><select value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option value="expense">Gasto</option><option value="external_income">Ingreso externo ajeno a ventas</option></select></FormField>{field("name", "Concepto", "text", false)}{field("amount", "Importe", "number", false)}<FormField label="Categoría" required><select value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}><option value="">Elegir</option>{categories.map(category => <option key={category}>{category}</option>)}</select></FormField><FormField label="Naturaleza"><select value={form.nature} onChange={event => setForm({ ...form, nature: event.target.value })}><option value="fixed">Fijo</option><option value="variable">Variable</option><option value="extraordinary">Extraordinario</option></select></FormField><FormField label="Alcance"><select value={form.scope === "general" ? "" : form.locationId || "__location"} onChange={event => setForm({ ...form, scope: event.target.value ? "location" : "general", locationId: event.target.value })}><option value="">General del negocio</option>{locationOptions.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></FormField>{field("accruedOn", "Devengamiento", "date", false)}{field("dueOn", "Vencimiento", "date")}{field("paidOn", "Pago efectivo", "date")}{form.paidOn ? <FormField label="Origen / destino del dinero"><select value={form.cashAccount} onChange={event => setForm({ ...form, cashAccount: event.target.value })}><option value="">Elegir</option><option value="cash">Efectivo</option><option value="bank">Cuenta bancaria</option></select></FormField> : null}{field("reference", "Referencia / comprobante", "text", form.type !== "external_income")}</div>
      <details><summary>Vínculos y observaciones opcionales</summary><div className="fm-crm-filters">{field("supplierId", "ID proveedor")}{field("orderId", "ID pedido")}{field("shipmentId", "ID envío")}{field("notes", "Observaciones")}</div></details>{message.startsWith("Error") ? <Toast tone="error">{message}</Toast> : null}
    </Modal>
    <Modal open={Boolean(settlement)} onClose={() => !busy && setSettlement(null)} title="Registrar acreditación con evidencia" description="Registro manual de evidencia verificable; no consulta ni mueve dinero en el banco." footer={<Button loading={busy} onClick={() => act(async () => { await recordSettlement(profile, settlement, settlementForm); setSettlement(null); })}>Guardar evidencia</Button>}>
      {[["amount", "Importe acreditado", "number"], ["paidOn", "Fecha efectiva", "date"], ["reference", "Referencia bancaria / comprobante", "text"]].map(([key, label, type]) => <FormField key={key} label={label} required><input type={type} step={type === "number" ? "0.01" : undefined} value={settlementForm[key]} onChange={event => setSettlementForm({ ...settlementForm, [key]: event.target.value })} /></FormField>)}{message.startsWith("Error") ? <Toast tone="error">{message}</Toast> : null}
    </Modal>
    <Modal open={Boolean(resolution)} onClose={() => !busy && setResolution(null)} title={resolution?.type === "cancel" ? "Anular movimiento" : "Resolver discrepancia manualmente"} description="El motivo queda registrado en Actividad / Auditoría." footer={<Button loading={busy} onClick={() => act(async () => { if (resolution.type === "cancel") await cancelFinancialEntry(profile, resolution.entry, reason); else { const part = resolution.part; await resolveFinanceAlert(profile, part.id, `${part.state}: ${part.saleCode}`, reason); } setResolution(null); })}>Confirmar con motivo</Button>}><FormField label="Motivo" required><textarea value={reason} onChange={event => setReason(event.target.value)} /></FormField>{message.startsWith("Error") ? <Toast tone="error">{message}</Toast> : null}</Modal>
  </div>;
}
