export const businessModules = [
  {
    id: "locations",
    number: "01",
    label: "Ubicaciones",
    shortLabel: "Ubicaciones",
    description: "Locales, ferias, vendedores, stock y ventas físicas.",
    collection: "locations",
    icon: "MapPin",
    accent: "gold",
    primaryAction: "Nueva ubicación",
  },
  {
    id: "quick-sales",
    number: "02",
    label: "Ventas rápidas",
    shortLabel: "Venta rápida",
    description: "Operaciones de WhatsApp, Instagram, teléfono y carga manual.",
    collection: "sales",
    icon: "ReceiptText",
    accent: "gold",
    primaryAction: "Venta rápida",
  },
  {
    id: "loyal-customers",
    number: "03",
    label: "Clientes fidelizados",
    shortLabel: "Clientes",
    description: "Historial, segmentos, consentimientos y próximos contactos.",
    collection: "customers",
    icon: "UsersRound",
    accent: "olive",
    primaryAction: "Nuevo cliente",
  },
  {
    id: "metrics",
    number: "04",
    label: "Métricas generales",
    shortLabel: "Métricas",
    description: "Resultados consolidados con consultas acotadas y resúmenes diarios.",
    collection: "dailySummaries",
    icon: "ChartNoAxesCombined",
    accent: "wood",
  },
  {
    id: "finance",
    number: "05",
    label: "Administración financiera",
    shortLabel: "Finanzas",
    description: "Ingresos, egresos, caja, márgenes y facturación pendiente.",
    collection: "financialEntries",
    icon: "CircleDollarSign",
    accent: "wood",
    primaryAction: "Nuevo movimiento",
    sensitive: true,
  },
  {
    id: "warehouse",
    number: "06",
    label: "Depósito",
    shortLabel: "Depósito",
    description: "Existencias centrales, transferencias, recepción y conteos.",
    collection: "stockTransfers",
    icon: "Warehouse",
    accent: "olive",
    primaryAction: "Transferir stock",
  },
  {
    id: "ecommerce",
    number: "07",
    label: "Página web y ecommerce",
    shortLabel: "Ecommerce",
    description: "Catálogo maestro, publicación, pedidos y configuración comercial.",
    collection: "orders",
    icon: "Store",
    accent: "gold",
  },
  {
    id: "social",
    number: "08",
    label: "Redes sociales",
    shortLabel: "Redes",
    description: "Consultas, oportunidades, responsables y conversiones por canal.",
    collection: "socialLeads",
    icon: "MessagesSquare",
    accent: "olive",
    primaryAction: "Nueva consulta",
  },
  {
    id: "marketing",
    number: "09",
    label: "Marketing",
    shortLabel: "Marketing",
    description: "Campañas, calendario, contenidos, presupuesto y resultados.",
    collection: "campaigns",
    icon: "Megaphone",
    accent: "gold",
    primaryAction: "Nueva campaña",
  },
  {
    id: "shipping",
    number: "10",
    label: "Gestión de envíos",
    shortLabel: "Envíos",
    description: "Preparación, responsables, seguimiento y entregas del día.",
    collection: "shipments",
    icon: "Truck",
    accent: "olive",
    primaryAction: "Nuevo envío",
  },
  {
    id: "alerts",
    number: "11",
    label: "Alertas",
    shortLabel: "Alertas",
    description: "Prioridades operativas visibles sólo para responsables autorizados.",
    collection: "alerts",
    icon: "Bell",
    accent: "error",
  },
  {
    id: "suppliers",
    number: "12",
    label: "Gestión de proveedores",
    shortLabel: "Proveedores",
    description: "Proveedores, compras, recepciones, costos y reposición.",
    collection: "suppliers",
    icon: "PackageSearch",
    accent: "wood",
    primaryAction: "Nueva compra",
  },
];

export const moduleById = Object.fromEntries(
  businessModules.map((module) => [module.id, module]),
);

export const managementRoutes = [
  { id: "dashboard", label: "Panel general", icon: "LayoutDashboard" },
  ...businessModules,
  { id: "actividad", label: "Actividad", icon: "Activity" },
  { id: "administration", label: "Administración", icon: "ShieldCheck" },
  { id: "audit", label: "Auditoría", icon: "ScrollText" },
  { id: "settings", label: "Configuración", icon: "Settings2" },
];

export const getManagementPath = (moduleId) =>
  moduleId === "dashboard" ? "/gestion" : `/gestion/${moduleId}`;
